
    const pageMap={home:'pageHome',electric:'pageElectric',water:'pageWater',notices:'pageNotices'};
    function showPage(key){Object.values(pageMap).forEach(id=>document.getElementById(id).classList.add('hidden'));document.getElementById(pageMap[key]).classList.remove('hidden');document.querySelectorAll('[data-nav]').forEach(b=>{const active=b.dataset.nav===key;b.className=`py-3 border-b-2 ${active?'border-indigo-600 text-indigo-600':'border-transparent text-slate-500'} whitespace-nowrap`});window.scrollTo({top:0,behavior:'smooth'})}
    function powerText(s){return {normal:'正常供电',violation:'违规停电',manual:'暂停供电',arrears:'欠费停电'}[s]||'状态未知'}
    function renderStudent(data){
      const r=data.room,w=data.water,normal=r.powerState==='normal';studentName.textContent=r.students[0]||'学生';studentAvatar.textContent=(r.students[0]||'学').slice(0,1);
      const roomNumber=(r.id||'').split('-').pop()||'';heroRoom.textContent=`${r.building} ${r.floor} ${roomNumber}室`;heroPeople.textContent=`当前登录：${r.students[0]||'学生'}${r.students.length>1?' · 室友：'+r.students.slice(1).join('、'):''}`;
      heroPowerStatus.className=`text-[10px] px-2 py-1 rounded-full font-bold ${normal?'bg-emerald-500/20 text-emerald-300':'bg-rose-500/20 text-rose-300'}`;heroPowerStatus.textContent=powerText(r.powerState);
      electricBadge.className=`px-2 py-1 rounded-full text-[10px] font-bold ${normal?'bg-emerald-50 text-emerald-600':'bg-rose-50 text-rose-600'}`;electricBadge.textContent=powerText(r.powerState);
      homeBalance.textContent=electricBalance.textContent=`¥ ${r.balance.toFixed(2)}`;homeBalance.className=`text-3xl font-bold mt-1 ${r.balance<=10?'text-rose-600':'text-slate-900'}`;balanceBar.style.width=Math.min(100,Math.max(2,r.balance))+'%';balanceHint.textContent=r.balance<=10?'余额偏低，请及时充值':`预计可用约 ${Math.max(1,Math.round(r.balance/3))} 天`;
      homeWaterBalance.textContent=waterBalance.textContent=`¥ ${w.balance.toFixed(2)}`;homeWaterUsage.textContent=waterMonth.textContent=`${w.monthLiters.toFixed(1)} L`;waterDeviceHint.textContent=`${w.meterId} · ${w.online?'在线':'离线'}`;waterMeter.textContent=w.meterId;waterState.textContent=`${w.online?'在线':'离线'} · 阀门${w.valve}`;
      monthKwh.textContent=electricMonth.textContent=`本月 ${r.monthKwh.toFixed(1)} kWh`;livePower.textContent=`${r.power.toFixed(2)} kW`;todayKwh.textContent=`${r.todayKwh.toFixed(1)} kWh`;
      homeBars.innerHTML=data.electricity.daily.map((d,i)=>`<div class="h-full flex-1 flex flex-col justify-end items-center gap-2"><i class="w-full max-w-7 bg-gradient-to-t from-indigo-600 to-indigo-400 rounded-t" style="height:${Math.max(18,d.kwh*10)}%"></i><span class="text-[9px] text-slate-400">${d.date}</span></div>`).join('');
      electricDaily.innerHTML=data.electricity.daily.slice().reverse().map(d=>`<div class="px-5 py-4 grid grid-cols-3 text-xs"><span class="text-slate-500">${d.date}</span><b>${d.kwh.toFixed(1)} kWh</b><span class="text-right">¥ ${d.fee.toFixed(2)}</span></div>`).join('');
      rechargeList.innerHTML=data.electricity.recharges.map(x=>`<div class="px-5 py-4 flex justify-between text-xs"><div><b class="text-emerald-600">+ ¥${x.amount.toFixed(2)}</b><p class="text-[10px] text-slate-400 mt-1">${x.channel} · ${x.time}</p></div><span class="text-emerald-600">到账成功</span></div>`).join('');
      waterRecords.innerHTML=w.records.map(x=>`<div class="px-5 py-4 grid grid-cols-2 md:grid-cols-4 items-center text-xs gap-2"><div><b>${x.liters.toFixed(1)} L</b><p class="text-[10px] text-slate-400 mt-1">${x.time}</p></div><span>${x.place}</span><span class="text-slate-400 hidden md:block">${x.id}</span><b class="text-right text-sky-600">- ¥${x.amount.toFixed(2)}</b></div>`).join('');
      const notes=data.notifications,unread=notes.filter(n=>!n.read).length;noticeDot.classList.toggle('hidden',unread===0);unreadCount.textContent=`${unread} 条未读`;notificationList.innerHTML=notes.length?notes.map(n=>`<div class="w-full px-5 py-4 flex gap-3 hover:bg-slate-50 ${n.read?'opacity-60':''}"><span class="w-9 h-9 rounded-xl flex items-center justify-center ${n.level==='danger'?'bg-rose-50 text-rose-600':n.level==='success'?'bg-emerald-50 text-emerald-600':'bg-amber-50 text-amber-600'}">${n.type==='power'?'⚡':'🔔'}</span><div class="flex-1"><div class="flex justify-between"><b class="text-xs">${n.title}</b><span class="text-[10px] text-slate-400">${n.time}</span></div><p class="text-[11px] text-slate-500 mt-1">${n.text}</p><div class="flex gap-3 mt-2">${n.read?'':`<button onclick="readNotice('${n.id}')" class="text-[10px] text-indigo-600 font-bold">标为已读</button>`}<button onclick="deleteNotice('${n.id}')" class="text-[10px] text-rose-500 font-bold">删除通知</button></div></div></div>`).join(''):'<div class="py-16 text-center text-xs text-slate-400">暂无通知</div>';
      const urgent=notes.find(n=>!n.read&&(n.level==='danger'||n.level==='warning'));importantNotice.className=urgent?'flex gap-3 items-start p-4 bg-amber-50 border border-amber-200 rounded-xl':'hidden';if(urgent)importantNotice.innerHTML=`<span>🔔</span><div class="flex-1 min-w-0"><b class="text-xs text-amber-800">${urgent.title}</b><p class="text-[11px] text-amber-700 mt-1">${urgent.text}</p></div><button onclick="handleUrgent()" class="shrink-0 self-center px-3 py-1.5 bg-amber-500 hover:bg-amber-600 text-white rounded-lg text-[11px] font-bold whitespace-nowrap">立即处理</button>`;
      const activity=[...w.records.slice(0,2).map(x=>({icon:'💧',title:`取水 ${x.liters} L`,sub:`${x.place} · ¥${x.amount.toFixed(2)}`,time:x.time})),...data.electricity.recharges.slice(0,2).map(x=>({icon:'¥',title:'电费充值成功',sub:`${x.channel} · +¥${x.amount.toFixed(2)}`,time:x.time}))];recentActivity.innerHTML=activity.slice(0,4).map(x=>`<div class="flex gap-3 p-3 bg-slate-50 rounded-xl"><span>${x.icon}</span><div><b class="text-xs">${x.title}</b><p class="text-[10px] text-slate-400 mt-1">${x.sub}</p></div></div>`).join('');
    }
    function openRecharge(){rechargeModal.classList.remove('hidden');rechargeModal.classList.add('flex')}function closeRecharge(){rechargeModal.classList.add('hidden');rechargeModal.classList.remove('flex')}function pickAmount(btn,v){document.querySelectorAll('#amountButtons button').forEach(x=>x.className='py-3 border border-slate-200 rounded-xl');btn.className='py-3 border border-indigo-500 bg-indigo-50 text-indigo-600 rounded-xl font-bold';rechargeAmount.value=v}function confirmRecharge(){const v=Number(rechargeAmount.value);if(v<=0)return toastMsg('请输入有效金额');CampusStore.recharge(v,'学生微信在线缴费');closeRecharge();toastMsg(`充值 ¥${v.toFixed(2)} 成功，已同步至管理端`)}function simulateElectricity(){const cur=CampusStore.get();if(cur.room.powerState!=='normal'){const map={violation:'违规停电中，无法模拟用电',manual:'管理员已暂停供电，无法模拟用电',arrears:'欠费停电，请先充值'};CampusStore.addElectricUsage(1);toastMsg(map[cur.room.powerState]||'停电中，无法用电');return}const before=cur.room.balance;CampusStore.addElectricUsage(1);toastMsg(before>0?'已产生 1 kWh 测试用电并完成扣费':'余额为 0，请先充值电费')}function rechargeWater(){CampusStore.rechargeWater(10);toastMsg('饮水账户测试充值 ¥10 成功')}function simulateWater(){const before=CampusStore.get();if(!before.water.online){CampusStore.addWaterRecord(1,'本层直饮水机');toastMsg('当前水表离线，无法下发开阀指令');return}if(before.water.balance<0.5){CampusStore.addWaterRecord(1,'本层直饮水机');toastMsg('饮水余额不足，请先测试充值');return}CampusStore.addWaterRecord(1,'本层直饮水机');toastMsg('平台鉴权成功，已开阀计量并扣费 ¥0.50')}function readNotice(id){CampusStore.markRead(id)}function handleUrgent(){const n=CampusStore.get().notifications.find(n=>!n.read&&(n.level==='danger'||n.level==='warning'));if(!n)return;if(n.type==='balance'||/欠费|余额|充值/.test(n.title))openRecharge();else showPage('notices')}function deleteNotice(id){CampusStore.deleteNotification(id);toastMsg('通知已删除')}async function logout(){await fetch('/api/logout',{method:'POST'});location.href='/login.html'}async function deleteAccount(){if(!confirm('注销后将永久删除账号、水电数据和通知，且无法恢复。确定继续吗？'))return;const response=await fetch('/api/account',{method:'DELETE'});if(response.ok){location.href='/login.html'}else{const data=await response.json().catch(()=>({}));toastMsg(data.error||'注销失败，请稍后重试')}}let timer;function toastMsg(t){toast.textContent='✓ '+t;toast.classList.remove('hidden');clearTimeout(timer);timer=setTimeout(()=>toast.classList.add('hidden'),2800)}
    CampusStore.subscribe(renderStudent);renderStudent(CampusStore.get());rechargeModal.addEventListener('click',e=>{if(e.target===rechargeModal)closeRecharge()});
  